In [291]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn import metrics
import numpy as np


currency_list = ['USDCHF10080',
                 'GBPUSD10080', 'EURUSD10080', 'USDJPY10080', 'USDCAD10080', 'AUDUSD10080', 'NZDUSD10080',
                 'GBPCHF10080', 'EURCHF10080', 'CHFJPY10080', 'CADCHF10080', 'AUDCHF10080', 'NZDCHF10080', 'EURGBP10080',
                 'GBPJPY10080', 'GBPCAD10080', 'GBPAUD10080', 'EURJPY10080', 'EURCAD10080', 'EURAUD10080', 'EURNZD10080',
                'CADJPY10080', 'AUDJPY10080', 'NZDJPY10080', 'AUDCAD10080', 'NZDCAD10080', 'AUDNZD10080'
                ]

In [292]:
# #loops through all currency, identify timeframes not in nzdcad and save them in global_available_timeframes list

headers = ['date_start', 'ignore', 'open', 'high', 'low', 'close', 'volume'  ]
shortest_row_currency = pd.read_csv('recent_data/' + 'NZDCAD10080' + '.csv', names=headers  )  

shortest_row_currency_timeframes = shortest_row_currency['date_start']



shortest_row_currency_timeframes = shortest_row_currency_timeframes.values.tolist()




global_unavailable_timeframes = []
for x in currency_list:
    
    
    current_currency_data = pd.read_csv('recent_data/' + x + '.csv', names=headers  )  
    
    current_currency_data_timeframes = current_currency_data['date_start']
   
    current_currency_data_timeframes = current_currency_data_timeframes.values.tolist()
   
    for y in shortest_row_currency_timeframes:
        
            if y not in current_currency_data_timeframes :
                
                global_unavailable_timeframes.append(y)
                

# this get the unique time frames because time frames could have been duplicated from different currencies 
global_unavailable_timeframes = np.unique(global_unavailable_timeframes)   


print(len(global_unavailable_timeframes))   
print(len(shortest_row_currency_timeframes))

20
727

In [293]:
#removes the identified time frame nzdcad timeframe list to ensure that all timeframe in nzdcad list have 
#data in other currencies

globally_available_time_frame=[]

for x in global_unavailable_timeframes:
    
    shortest_row_currency_timeframes.remove(x)
    
globally_available_time_frame = shortest_row_currency_timeframes

print(len(globally_available_time_frame))

707

In [294]:
# loop through all currency pairs, get the needed rows from them and assemble all rows to form a combine_data_dataframe

combine_data_dataframe = pd.DataFrame(data={}, index = pd.Series(range(0,len(globally_available_time_frame))), )

for x in currency_list :
    
    

    current_currency_data = pd.read_csv('recent_data/' + x + '.csv', names=headers  )    

    current_currency_volume = []
    
    current_currency_open = []
    current_currency_high = []
    current_currency_low = []
    current_currency_close = []

    q = 0

    for y in globally_available_time_frame:

        for index, row in current_currency_data.iterrows():

            if y  == row.date_start:            
                        
                current_currency_volume.append(row.volume)            
                current_currency_open.append(row.open)
                current_currency_high.append(row.high)
                current_currency_low.append(row.low)
                current_currency_close.append(row.close)
                        

    # this function takes a list and returns with a list of 5 list that is the data for the previous row
    
    def add_5_columns(real_column) :
        
        current_currency_column_add_on = [real_column, [], [], [], [], []]
        
        g = 1 
        
        while g < 6:
            
            current_currency_column_add_on[g] = current_currency_column_add_on[g-1].copy()
            current_currency_column_add_on[g].pop(0)
            current_currency_column_add_on[g].append(0)    
            g = g+1
            
        current_currency_column_add_on.pop(0)
        return current_currency_column_add_on
            
            
           

    combine_data_dataframe[ x +'_volume'] = current_currency_volume
    
    volume_columns = add_5_columns(current_currency_volume)
    
    for h in volume_columns:
        mini_df = pd.DataFrame(data={}, index = pd.Series(range(0,len(globally_available_time_frame))), )
        mini_df[''] = h   
        combine_data_dataframe = pd.concat([ combine_data_dataframe, mini_df], axis=1)
    
   
    
    
    combine_data_dataframe[ x +'_open'] = current_currency_open
    
    open_columns = add_5_columns(current_currency_open)
    
    for h in open_columns:
        mini_df = pd.DataFrame(data={}, index = pd.Series(range(0,len(globally_available_time_frame))), )
        mini_df[''] = h   
        combine_data_dataframe = pd.concat([ combine_data_dataframe, mini_df], axis=1)
    
    
    
    combine_data_dataframe[ x +'_high'] = current_currency_high   
    
    high_columns = add_5_columns(current_currency_high)
    
    for h in high_columns:
        mini_df = pd.DataFrame(data={}, index = pd.Series(range(0,len(globally_available_time_frame))), )
        mini_df[''] = h   
        combine_data_dataframe = pd.concat([ combine_data_dataframe, mini_df], axis=1)
    
    
    
    combine_data_dataframe[ x +'_low'] = current_currency_low
    
    low_columns = add_5_columns(current_currency_low)
    
    for h in low_columns:
        mini_df = pd.DataFrame(data={}, index = pd.Series(range(0,len(globally_available_time_frame))), )
        mini_df[''] = h   
        combine_data_dataframe = pd.concat([ combine_data_dataframe, mini_df], axis=1)
    
    
    
    combine_data_dataframe[ x +'_close'] = current_currency_close
    
   
    
    print(x)

USDCHF10080
GBPUSD10080
EURUSD10080
USDJPY10080

C:\Users\AKINSH~1\AppData\Local\Temp/ipykernel_22636/312645071.py:54: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  combine_data_dataframe[ x +'_volume'] = current_currency_volume
C:\Users\AKINSH~1\AppData\Local\Temp/ipykernel_22636/312645071.py:66: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  combine_data_dataframe[ x +'_open'] = current_currency_open
C:\Users\AKINSH~1\AppData\Local\Temp/ipykernel_22636/312645071.py:77: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  combine_data_dataframe[ x +'_high'] = current_currency_high
C:\Users\AKINSH~1\AppData\Local\Temp/ipykernel_22636/312645071.py:88: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  combine_data_dataframe[ x +'_low'] = current_currency_low
C:\Users\AKINSH~1\AppData\Local\Temp/ipykernel_22636/312645071.py:99: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider using pd.concat instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  combine_data_dataframe[ x +'_close'] = current_currency_close

USDCAD10080
AUDUSD10080
NZDUSD10080
GBPCHF10080
EURCHF10080
CHFJPY10080
CADCHF10080
AUDCHF10080
NZDCHF10080
EURGBP10080
GBPJPY10080
GBPCAD10080
GBPAUD10080
EURJPY10080
EURCAD10080
EURAUD10080
EURNZD10080
CADJPY10080
AUDJPY10080
NZDJPY10080
AUDCAD10080
NZDCAD10080
AUDNZD10080

In [295]:
combine_data_dataframe

,USDCHF10080_volume,,,,,,USDCHF10080_open,,,,...,,,,AUDNZD10080_low,,,,,,AUDNZD10080_close
0,150871,143626,128138,154705,182181,196133,0.91594,0.91494,0.91364,0.90439,...,1.05647,1.06061,1.06126,1.04031,1.04171,1.04523,1.04488,1.05163,1.05418,1.04216
1,143626,128138,154705,182181,196133,188258,0.91494,0.91364,0.90439,0.91854,...,1.06061,1.06126,1.07383,1.04171,1.04523,1.04488,1.05163,1.05418,1.05545,1.04409
2,128138,154705,182181,196133,188258,211305,0.91364,0.90439,0.91854,0.91798,...,1.06126,1.07383,1.07269,1.04523,1.04488,1.05163,1.05418,1.05545,1.06324,1.04669
3,154705,182181,196133,188258,211305,217632,0.90439,0.91854,0.91798,0.91352,...,1.07383,1.07269,1.07642,1.04488,1.05163,1.05418,1.05545,1.06324,1.06940,1.04849
4,182181,196133,188258,211305,217632,216303,0.91854,0.91798,0.91352,0.91999,...,1.07269,1.07642,1.07985,1.05163,1.05418,1.05545,1.06324,1.06940,1.07220,1.05288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,49816,41189,36502,39821,40720,0,1.18860,1.18640,1.20790,1.20070,...,1.17220,1.15840,0.00000,1.15890,1.16860,1.16290,1.14070,1.14020,0.00000,1.16440
703,41189,36502,39821,40720,0,0,1.18640,1.20790,1.20070,1.20720,...,1.15840,0.00000,0.00000,1.16860,1.16290,1.14070,1.14020,0.00000,0.00000,1.18030
704,36502,39821,40720,0,0,0,1.20790,1.20070,1.20720,0.00000,...,0.00000,0.00000,0.00000,1.16290,1.14070,1.14020,0.00000,0.00000,0.00000,1.19540
705,39821,40720,0,0,0,0,1.20070,1.20720,0.00000,0.00000,...,0.00000,0.00000,0.00000,1.14070,1.14020,0.00000,0.00000,0.00000,0.00000,1.16600
706,40720,0,0,0,0,0,1.20720,0.00000,0.00000,0.00000,...,0.00000,0.00000,0.00000,1.14020,0.00000,0.00000,0.00000,0.00000,0.00000,1.14590

In [296]:
#create and add the timeframe column to the combine_data_data_frame to be able to identify each rows

date_series = pd.Series(globally_available_time_frame)

# the code below convert it to panda date time object
date_series = pd.to_datetime(date_series)


#turning date_series to a data frame so as to be able to add it as the first column 
date_series_dataframe =  pd.DataFrame(data={}, index = pd.Series(range(0, len(globally_available_time_frame))), )
date_series_dataframe['date_start'] = date_series

#the two dataframes are combined along the y axis to form one dataframe with all information and date
combine_data_dataframe = pd.concat([ date_series_dataframe, combine_data_dataframe], axis=1)

combine_data_dataframe

,date_start,USDCHF10080_volume,,,,,,USDCHF10080_open,,,...,,,,AUDNZD10080_low,,,,,,AUDNZD10080_close
0,2021-08-22,150871,143626,128138,154705,182181,196133,0.91594,0.91494,0.91364,...,1.05647,1.06061,1.06126,1.04031,1.04171,1.04523,1.04488,1.05163,1.05418,1.04216
1,2021-08-15,143626,128138,154705,182181,196133,188258,0.91494,0.91364,0.90439,...,1.06061,1.06126,1.07383,1.04171,1.04523,1.04488,1.05163,1.05418,1.05545,1.04409
2,2021-08-08,128138,154705,182181,196133,188258,211305,0.91364,0.90439,0.91854,...,1.06126,1.07383,1.07269,1.04523,1.04488,1.05163,1.05418,1.05545,1.06324,1.04669
3,2021-08-01,154705,182181,196133,188258,211305,217632,0.90439,0.91854,0.91798,...,1.07383,1.07269,1.07642,1.04488,1.05163,1.05418,1.05545,1.06324,1.06940,1.04849
4,2021-07-25,182181,196133,188258,211305,217632,216303,0.91854,0.91798,0.91352,...,1.07269,1.07642,1.07985,1.05163,1.05418,1.05545,1.06324,1.06940,1.07220,1.05288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,2007-09-16,49816,41189,36502,39821,40720,0,1.18860,1.18640,1.20790,...,1.17220,1.15840,0.00000,1.15890,1.16860,1.16290,1.14070,1.14020,0.00000,1.16440
703,2007-09-09,41189,36502,39821,40720,0,0,1.18640,1.20790,1.20070,...,1.15840,0.00000,0.00000,1.16860,1.16290,1.14070,1.14020,0.00000,0.00000,1.18030
704,2007-09-02,36502,39821,40720,0,0,0,1.20790,1.20070,1.20720,...,0.00000,0.00000,0.00000,1.16290,1.14070,1.14020,0.00000,0.00000,0.00000,1.19540
705,2007-08-26,39821,40720,0,0,0,0,1.20070,1.20720,0.00000,...,0.00000,0.00000,0.00000,1.14070,1.14020,0.00000,0.00000,0.00000,0.00000,1.16600
706,2007-08-19,40720,0,0,0,0,0,1.20720,0.00000,0.00000,...,0.00000,0.00000,0.00000,1.14020,0.00000,0.00000,0.00000,0.00000,0.00000,1.14590

In [298]:
# copies the data frame so as to isolate the first 10 rows for prediction
combine_top_10_rows_dataframe = combine_data_dataframe.copy(deep=True)


combine_top_10_rows_dataframe = combine_top_10_rows_dataframe.head(10)

#saves the first 10 rows to excel

#combine_top_10_rows_dataframe.to_excel("files/combine_top_10_rows_dataframe.xlsx")



combine_data_dataframe = combine_data_dataframe.head( len(globally_available_time_frame) - 5 )

#combine_data_dataframe.to_excel("files/combine_data_dataframe.xlsx")